[package]
name = "ice-kola"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icicle-vm = { path = "../icicle-emu/icicle-vm" }
pcode = { path = "../icicle-emu/sleigh/pcode" }
